daily66/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('main.urls', namespace="main")),
]

main/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from main.forms import LoginForm
from main.views import HabitCreate, HabitUpdate, HabitDelete, LogCreate, \
    LogUpdate, LogDelete
import main.views

urlpatterns = [
    url(r'^$', main.views.index, name="index"),
    url(r'^@(?P<username>[\w-]+)/$', main.views.user_page, name="user-page"),
    url(r'^habit/(?P<pk>\d+)/$', main.views.habit_detail,
        name="habit-detail"),
    url(r'^habit/add/$', HabitCreate.as_view(), name="habit-add"),
    url(r'^habit/(?P<pk>\d+)/edit/$', HabitUpdate.as_view(),
        name="habit-edit"),
    url(r'^habit/(?P<pk>\d+)/delete/$', HabitDelete.as_view(),
        name="habit-delete"),
    url(r'^habit/(?P<pk>\d+)/newlog/$', LogCreate.as_view(), name="log-add"),
    url(r'^log/(?P<pk>\d+)/edit/$', LogUpdate.as_view(), name="log-edit"),
    url(r'^log/(?P<pk>\d+)/delete/$', LogDelete.as_view(), name="log-delete"),
    url(r'^accounts/join/$', main.views.join_view, name='join'),
    url(r'^accounts/login/$', auth_views.login,
        {'template_name': 'main/login.html',
         'authentication_form': LoginForm}, name='login'),
    url(r'^accounts/logout/$', main.views.logout_view, name="logout"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse


class Habit(models.Model):
    user = models.ForeignKey(User)
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return "{} - {}".format(self.title, self.user.username)

    def get_absolute_url(self):
        return reverse('main:habit-detail', args=[self.pk])


class Log(models.Model):
    habit = models.ForeignKey(Habit)
    date = models.DateField()
    content = models.CharField(max_length=500)
    score = models.IntegerField()

    def __str__(self):
        return "{} - {}".format(self.date, self.habit)

    def get_absolute_url(self):
        return reverse('main:habit-detail', args=[self.habit.pk])

main/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.utils.translation import ugettext, ugettext_lazy as _
from main.models import Habit, Log
import datetime


alphanumeric = RegexValidator(
    r'^[0-9a-z]*$', 'Only alphanumeric(0-9a-z) characters are allowed.')


class UserCreationForm(forms.ModelForm):
    error_messages = {
        'duplicate_email': _("Email addresses must be unique."),
        'password_mismatch': _("The two password fields didn't match."),
    }
    username = forms.CharField(
        max_length=30,
        widget=forms.TextInput(attrs={'class': "form-control"}),
        validators=[alphanumeric])
    email = forms.CharField(
        max_length=254,
        widget=forms.EmailInput(attrs={'class': "form-control"}), )
    password1 = forms.CharField(label=_("Password"),
        widget=forms.PasswordInput(attrs={'class': "form-control"}))
    password2 = forms.CharField(label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={'class': "form-control"}),
        help_text=_("Enter the same password as above, for verification."))

    class Meta:
        model = User
        fields = ("username", "email", )

    def clean_email(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if email and User.objects.filter(email=email)\
                .exclude(username=username).count():
            raise forms.ValidationError(
                self.error_messages['duplicate_email'],
                code='duplicate_email',
            )
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        max_length=30,
        widget=forms.TextInput(attrs={'class': "form-control"}), )
    password = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput(attrs={'class': "form-control"}), )


class HabitForm(forms.ModelForm):
    title = forms.CharField(
        max_length=200,
        widget=forms.TextInput(attrs={'class': "form-control"}), )
    description = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={'class': "form-control"}), )
    class Meta:
        model = Habit
        fields = ('title', 'description')


class LogForm(forms.ModelForm):
    date = forms.DateField(
        initial=datetime.date.today,
        widget=forms.DateInput(attrs={'class': "form-control",
                                      'type': "date"}), )
    content = forms.CharField(
        max_length=500,
        widget=forms.TextInput(attrs={'class': "form-control"}), )
    score = forms.IntegerField(
        widget=forms.TextInput(attrs={'class': "form-control",
                                      'type': "number"}), )
    class Meta:
        model = Log
        fields = ('date', 'content', 'score')

main/views.py
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth import logout
from django.http.response import HttpResponseRedirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse, reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from main.models import Habit, Log
from main.forms import HabitForm, LogForm, UserCreationForm

def join_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(username=request.POST['username'],
                                password=request.POST['password1'])
            login(request, user)
            return HttpResponseRedirect('/')
    else:
        form = UserCreationForm()
    return render(request, 'main/join.html', {'form': form, })


def logout_view(request):
    logout(request)
    return redirect('main:index')


def index(request):
    user_list = User.objects.all()
    habit_list = Habit.objects.all()
    return render(request, 'main/index.html',
                  {'user_list': user_list, 'habit_list': habit_list, })


def user_page(request, username):
    user = User.objects.get(username=username)
    habits = Habit.objects.filter(user=user)
    return render(request, 'main/user_page.html',
                  {'page_user': username, 'habits': habits, })


def habit_detail(request, pk):
    habit = Habit.objects.get(pk=pk)
    logs = Log.objects.filter(habit=habit).order_by('-date')
    return render(request, 'main/habit_detail.html',
                  {'habit': habit, 'logs': logs, })


@method_decorator(login_required, name='dispatch')
class HabitCreate(CreateView):
    form_class = HabitForm
    template_name = 'main/habit_form.html'

    def form_valid(self, form):
        habit = form.save(commit=False)
        habit.user = self.request.user
        habit.save()
        return redirect(habit)


@method_decorator(login_required, name='dispatch')
class HabitUpdate(UpdateView):
    model = Habit
    form_class = HabitForm
    template_name = 'main/habit_form.html'

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.user != self.request.user:
            return redirect(obj)
        return super(HabitUpdate, self).dispatch(request, *args, **kwargs)

    def form_vaild(self, form):
        habit = Habit.objects.get(pk=self.object.pk)
        is_updated = form.cleaned_data['title'] != habit.title or \
            form.cleaned_data['description'] != habit.description
        if is_updated:
            habit = form.save()
            args = (habit.user.username, habit.pk)
            url = reverse('main:habit-detail', args=args)
        else:
            args = (self.object.user.username, self.object.id)
            url = reverse('main:habit-detail', args=args)
        return HttpResponseRedirect(url)


@method_decorator(login_required, name='dispatch')
class HabitDelete(DeleteView):
    model = Habit
    template_name = 'main/habit_delete_confirm.html'

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.user != self.request.user:
            return redirect(obj)
        return super(HabitDelete, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('main:user-page',
                            kwargs={'username': self.request.user.username})

    def delete(self, request, *args, **kwargs):
        return super(HabitDelete, self).delete(request, *args, **kwargs)


@method_decorator(login_required, name='dispatch')
class LogCreate(CreateView):
    form_class = LogForm
    template_name = 'main/log_form.html'

    def dispatch(self, request, *args, **kwargs):
        obj = get_object_or_404(Habit, pk=self.kwargs.get('pk'))
        if obj.user != self.request.user:
            return redirect(obj)
        return super(LogCreate, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        habit = get_object_or_404(Habit, pk=self.kwargs.get('pk'))
        log = form.save(commit=False)
        log.habit = habit
        log.save()
        return redirect(log.habit)


@method_decorator(login_required, name='dispatch')
class LogUpdate(UpdateView):
    model = Log
    form_class = LogForm
    template_name = 'main/log_form.html'

    def dispatch(self, request, *args, **kwargs):
        obj = get_object_or_404(Log, pk=self.kwargs.get('pk'))
        if obj.habit.user != self.request.user:
            return redirect(obj)
        return super(LogUpdate, self).dispatch(request, *args, **kwargs)

    def form_vaild(self, form):
        log = Log.objects.get(pk=self.object.pk)
        is_updated = form.cleaned_data['date'] != log.date or \
            form.cleaned_data['content'] != log.content or \
            form.cleaned_date['score'] != log.score
        if is_updated:
            log = form.save()
            args = (log.habit.user.username, log.habit.pk)
            url = reverse('main:habit-detail', args=args)
        else:
            args = (self.object.habit.user.username, self.object.habit.id)
            url = reverse('main:habit-detail', args=args)
        return HttpResponseRedirect(url)


@method_decorator(login_required, name='dispatch')
class LogDelete(DeleteView):
    model = Log
    template_name = 'main/log_delete_confirm.html'

    def dispatch(self, request, *args, **kwargs):
        obj = get_object_or_404(Log, pk=self.kwargs.get('pk'))
        if obj.habit.user != self.request.user:
            return redirect(obj)
        return super(LogDelete, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('main:habit-detail',
                            kwargs={'pk': self.object.habit.pk})

    def delete(self, request, *args, **kwargs):
        return super(LogDelete, self).delete(request, *args, **kwargs)

main/templates/main/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>{% block title %}Daily66{% endblock %}</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">
  {% load staticfiles %}
  <link rel="stylesheet" href="{% static 'main/main.css' %}">
</head>
<body>
  <nav class="navbar navbar-fixed-top navbar-dark bg-inverse">
    <div class="container">
      <a class="navbar-brand" href="{% url "main:index" %}">Daily66</a>
      <ul class="nav navbar-nav pull-xs-right">
        {% if user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url "main:user-page" user.username %}">
            {{ user.username }}
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "main:habit-add" %}">+ Habit</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "main:logout" %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url "main:join" %}">Sign Up</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "main:login" %}">Login</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <div class="container">
  {% block content %}
  {% endblock %}
  </div>
</body>
</html>

main/templates/main/habit_delete_confirm.html
{% extends "main/base.html" %}

{% block content %}
<h1>Delete habit</h1>
<form action="" method="post">{% csrf_token %}
  <p>Are you sure you want to delete "{{ object.title }}"?</p>
  <input class="btn btn-info" type="submit" value="Confirm">
</form>
{% endblock %}

main/templates/main/habit_detail.html
{% extends "main/base.html" %}

{% block content %}
<h1>{{ habit.title }}</h1>
{% if user == habit.user %}
<a href="{% url "main:habit-edit" habit.id %}">edit</a>
<a href="{% url "main:habit-delete" habit.id %}">delete</a>
{% endif %}
<p>{{ habit.description }}</p>
<h2><a href="{% url "main:user-page" habit.user.username %}">{{ habit.user.username }}</a></h2>
{% if user == habit.user %}
<a href="{% url "main:log-add" habit.id %}">+ Log</a>
{% endif %}
<ul>
  {% for log in logs %}
  <li>{{ log.date }} / {{ log.content }} / {{ log.score }}</li>
  {% if user == habit.user %}
  <a href="{% url "main:log-edit" log.id %}">edit</a>
  <a href="{% url "main:log-delete" log.id %}">delete</a>
  {% endif %}
  {% endfor %}
</ul>
{% endblock %}

main/templates/main/habit_form.html
{% extends "main/base.html" %}

{% block content %}
{% if habit.id %}
<h1>Edit habit</h1>
{% else %}
<h1>Create new habit</h1>
{% endif %}
{% if form.errors %}
{{ form.errors }}
{% endif %}
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
  <div class="form-group">
    <label for="id_title">Title</label>
    {{ form.title }}
  </div>
  <div class="form-group">
    <label for="id_description">Description</label>
    {{ form.description }}
  </div>
  <input class="btn btn-info" type="submit" value="Submit">
</form>
{% endblock %}

main/templates/main/index.html
{% extends "main/base.html" %}

{% block content %}
<div>
  <h2>User</h2>
  <ul>
    {% for user in user_list %}
    <li>
      <a href="{% url "main:user-page" user.username %}">{{ user.username }}</a>
    </li>
    {% endfor%}
  </ul>
</div>
<div>
  <h2>Habit</h2>
  <ul>
    {% for habit in habit_list %}
    <li>
      <a href="{% url "main:habit-detail" habit.id %}">{{ habit.title }}</a>
      by <a href="{% url "main:user-page" habit.user.username %}">{{ habit.user.username }}</a>
    </li>
    {% endfor%}
  </ul>
</div>
{% endblock %}

main/templates/main/join.html
{% extends "main/base.html" %}

{% block content %}
<h2>Join</h2>
  {% if form.non_field_errors %}
  <p>{{ form.non_field_errors}}</p>
  {% endif %}

  {% if user.is_authenticated %}
  <p>You already logged in.</p>
  {% else %}
  <form action="{%  url 'main:join' %}" method="post">{% csrf_token %}
    {% if form.username.errors %}
    <div class="form-group has-danger">
      <label for="id_username">Username</label>
      {{ form.username }}
      <ul>
        {% for error in form.username.errors %}
        <li>{{ error|escape }}</li>
        {% endfor %}
      </ul>
    </div>
    {% else %}
    <div class="form-group">
      <label for="id_username">Username</label>
      {{ form.username }}
    </div>
    {% endif %}

    {% if form.email.errors %}
    <div class="form-group has-danger">
      <label for="id_email">Email</label>
      {{ form.email }}
      <ul>
        {% for error in form.email.errors %}
        <li>{{ error|escape }}</li>
        {% endfor %}
      </ul>
    </div>
    {% else %}
    <div class="form-group">
      <label for="id_email">Email</label>
      {{ form.email }}
    </div>
    {% endif %}

    {% if form.password1.errors %}
    <div class="form-group has-danger">
      <label for="id_password">Password</label>
      {{ form.password1 }}
      <ul>
        {% for error in form.password1.errors %}
        <li>{{ error|escape }}</li>
        {% endfor %}
      </ul>
    </div>
    {% else %}
    <div class="form-group">
      <label for="id_password">Password</label>
      {{ form.password1 }}
    </div>
    {% endif %}

    {% if form.password2.errors %}
    <div class="form-group has-danger">
      <label for="id_password">Password confirmation</label>
      {{ form.password2 }}
      <ul>
        {% for error in form.password2.errors %}
        <li>{{ error|escape }}</li>
        {% endfor %}
      </ul>
    </div>
    {% else %}
    <div class="form-group">
      <label for="id_password">Password confirmation</label>
      {{ form.password2 }}
    </div>
    {% endif %}

    <button type="submit" value="signup" class="btn btn-info btn-block">
      Sign Up
    </button>
  </form>
  {% endif %}
{% endblock %}

main/templates/main/log_delete_confirm.html
{% extends "main/base.html" %}

{% block content %}
<h1>Delete log</h1>
<form action="" method="post">{% csrf_token %}
  <p>Are you sure you want to delete this log?</p>
  <input class="btn btn-info" type="submit" value="Confirm">
</form>
{% endblock %}

main/templates/main/log_form.html
{% extends "main/base.html" %}

{% block content %}
{% if log.id %}
<h1>Edit log</h1>
{% else %}
<h1>Create new log</h1>
{% endif %}
{% if form.errors %}
{{ form.errors }}
{% endif %}
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
  <div class="form-group">
    <label for="id_date">Date</label>
    {{ form.date }}
  </div>
  <div class="form-group">
    <label for="id_content">Content</label>
    {{ form.content }}
  </div>
  <div class="form-group">
    <label for="id_score">Score</label>
    {{ form.score }}
  </div>
  <input class="btn btn-info" type="submit" value="Submit">
</form>
{% endblock %}

main/templates/main/login.html
{% extends "main/base.html" %}

{% block content %}
<h2>Login</h2>
  {% if form.non_field_errors %}
  <p>{{ form.non_field_errors }}</p>
  {% endif %}

  {% if user.is_authenticated %}
  <p>You already logged in.</p>
  {% else %}
  <form method="post" action="{% url 'main:login' %}">{% csrf_token %}
    {% if form.username.errors %}
    <div class="form-group has-danger">
      <label for="id_username">Username</label>
      {{ form.username }}
      <ul>
        {% for error in form.username.errors %}
        <li>{{ error|escape }}</li>
        {% endfor %}
      </ul>
    </div>
    {% else %}
    <div class="form-group">
      <label for="id_username">Username</label>
      {{ form.username }}
    </div>
    {% endif %}

    {% if form.password.errors %}
    <div class="form-group has-danger">
      <label for="id_password">Password</label>
      {{ form.password }}
      <ul>
        {% for error in form.password.errors %}
        <li>{{ error|escape }}</li>
        {% endfor %}
      </ul>
    </div>
    {% else %}
    <div class="form-group">
    <label for="id_password">Password</label>
    {{ form.password }}
    </div>
    {% endif %}

    <button type="submit" value="login" class="btn btn-info btn-block">
      Login
    </button>
  </form>
  {% endif %}
{% endblock %}

main/templates/main/user_page.html
{% extends "main/base.html" %}

{% block content %}
<div>
  <h2>{{ page_user }}</h2>
</div>
<div>
  <ul>
    {% for habit in habits %}
    <li>
      <a href="{% url "main:habit-detail" habit.id %}">{{ habit.title }}</a>
    </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}